nome = str(input('Digite seu nome completo: ')).strip()
print('Analizando se nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
nome1 = nome.split()
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
print('Seu primeiro nome é {} e ele tem {} letras'.format(nome1[0], (len(nome1[0]))))
